### PR TITLE
Action component

### LINKED ISSUE #12: Action component
As discussed with @skjnldsv and @jancborchardt we should add a action component that will take a list of actions and render the action icon directly if there is only one. If multiple actions are added, a 3-dots menu with a popover menu should be shown.

### LINKED ISSUE #54: Linter fails
```
$ npm run lint

> nextcloud-vue@0.1.5 lint nextcloud-vue
> eslint --ext .js,.vue src tests


Oops! Something went wrong! :(

ESLint: 5.6.0.
No files matching the pattern "tests" were found.
Please check for typing mistakes in the pattern.
```

### PR DESCRIPTION
**Pull request by skjnldsv**
Fix #12 
Fix #54

### CODE REVIEW

File: src/components/Action/Action.vue [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+  - GNU Affero General Public License for more details.
+  -
+  - You should have received a copy of the GNU Affero General Public License
+  - along with this program. If not, see <http://www.gnu.org/licenses/>.
+  -
+  -->
+
+<template>
+	<!-- if only one action, check if we need to bind to click or not -->
+	<a :tabindex="actions.length === 1" :href="actions.length === 1 && actions[0].href ? actions[0].href : '#'"
```
Comment (ChristophWurst) [inline src/components/Action/Action.vue]: May I suggest to move some logic into a computed property? It's hard to comprehend what's going on here otherwise.

File: src/components/Action/Action.vue [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+		:class="[actions.length === 1 ? `${actions[0].icon} action-item--single` : 'action-item--multiple']"
+		v-on="actions.length === 1 && actions[0].action ? { click: actions[0].action } : {}">
+
+		<!-- If more than one action, create a popovermenu -->
+		<template v-if="actions.length > 1">
+			<span v-click-outside="closeMenu" tabindex="1" class="action-item__menutoggle icon-more"
+				@click="toggleMenu" />
+			<span :class="{ 'open': opened }" class="action-item__menu popovermenu">
```
Comment (ChristophWurst) [inline src/components/Action/Action.vue]: Is `action-item__menu` a real class? What's that used for?

Comment (skjnldsv) [reply src/components/Action/Action.vue]: Will be used for scoped design

File: src/components/Action/Action.vue (hunk 1 above)
Comment (skjnldsv) [reply src/components/Action/Action.vue]: I guess yes 🙈😂

File: src/components/Action/Action.vue [hunk 3]
```diff
@@ -0,0 +1,127 @@
...
+	components: {
+		PopoverMenu
+	},
+	directives: {
+		ClickOutside
+	},
+	props: {
+		actions: {
+			type: Array,
+			required: true,
```
Comment (ChristophWurst) [inline src/components/Action/Action.vue]: does `required: true` *and* a default make any sense? I guess the default will never be used.

Comment (skjnldsv) [reply src/components/Action/Action.vue]: I usually use the default as an example, because let's face it, no one will ever use the default yes :stuck_out_tongue_closed_eyes:

Comment (ChristophWurst) [reply src/components/Action/Action.vue]: I see. Let's move that into examples and/or documentation then :wink:

Comment (skjnldsv) [reply src/components/Action/Action.vue]: Later then, on the jsDoc one?

Comment (ChristophWurst) [reply src/components/Action/Action.vue]: Yes!

**Comment by skjnldsv** [comment]
Bump for reviews then :rocket:

**Comment by ChristophWurst** [comment]
Tested it as a replacement of the popovermenu in Mail's envelope component:

- [x] renders a single action nicely
- [ ] single action should have a tooltip
- [x] multiple actions render a popover menu
- [ ] popover menu positioning is a bit off
- [ ] popover menu entries should have a lower opacity (entries and icons are displayed black)

**Comment by ChristophWurst** [comment]
> popover menu positioning is a bit off

## Current state
bildschirmfoto von 2018-11-02 09-18-42
## Locally fixed
bildschirmfoto von 2018-11-02 09-18-34

## Fix
bildschirmfoto von 2018-11-02 09-18-26

**Comment by skjnldsv** [comment]
The popovermenu requires a fix on the server.
The right alignment is wrong :) (-5 instead of -2)
capture d ecran_2018-11-02_09-51-33

**Comment by ChristophWurst** [comment]
> The popovermenu requires a fix on the server.

Fix it!

**Comment by skjnldsv** [comment]
> > The popovermenu requires a fix on the server.
> 
> Fix it!

https://github.com/nextcloud/server/pull/12207
